    package ogre.maze

    object OgreMaze {

      abstract class level extends Solver with StringParserTerrain

      object level1 extends level {
        val level = """@@........
                      |@@O.......
                      |.....O.O..
                      |..........
                      |..O.O.....
                      |..O....O.O
                      |.O........
                      |..........
                      |.....OO...
                      |.........$""".stripMargin
      }

      object level2 extends level {
        val level = """@@........
                      |@@O.......
                      |.....O.O..
                      |..........
                      |..O.O.....
                      |..O....O.O
                      |.O........
                      |..........
                      |.....OO.O.
                      |.........$""".stripMargin
      }

      object level3 extends level {
        val level = """$.O...O...
                      |...O......
                      |..........
                      |O..O..O...
                      |..........
                      |O..O..O...
                      |..........
                      |......OO..
                      |O..O....@@
                      |........@@""".stripMargin
      }

      object level4 extends level {
        val level = """.@@.....O.
                      |.@@.......
                      |..O..O....
                      |.......O..
                      |...O......
                      |..........
                      |.......O.O
                      |...O.O....
                      |.......O..
                      |.........$""".stripMargin
      }


      def main(args: Array[String]) {
        println(level1.solutionString(level1.solution, level1.startOgre, level1.vector) + "\n")
        println(level2.solutionString(level2.solution, level2.startOgre, level2.vector) + "\n")
        println(level3.solutionString(level3.solution, level3.startOgre, level3.vector) + "\n")
        println(level4.solutionString(level4.solution, level4.startOgre, level4.vector) + "\n")
      }

    }
